version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000" # コンテナの8000番ポートをローカル8000番へ
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_PAGER: ""
    volumes:
      # 外部スクリプトをマウント
      - ./scripts/init-dynamodb.sh:/init-dynamodb.sh:ro
    entrypoint: [ "sh", "/init-dynamodb.sh" ]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: fastapi
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      DYNAMODB_PRODUCT_TABLE_NAME: products
      DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

volumes:
  dynamodb_data:
