version: "3"
tasks:

  test:
    desc: "python test"
    cmds:
      - uv run --group dev pytest

  local-run:
    desc: "run local dev server"
    cmds:
      - uv run uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload

  local:
    desc: "start local dev server"
    cmds:
      - docker compose -f docker-compose.dev.yml up --build

  check:
    desc: "lint check"
    deps: [test]
    cmds:
      - uv run --group dev ruff check .
      - uv run --group dev mypy .
      - uv run --group dev bandit -r api

  all-check:
    desc: "all check"
    cmds:
      - docker build -f Dockerfile.check --rm .

  behave:
    desc: "run behave BDD tests"
    cmds:
      - docker compose -f docker-compose.behave.yml up --build
