version: "3"
tasks:

  test:
    desc: "python test"
    cmds:
      - uv run --group dev pytest

  local:
    desc: "start local dev server"
    cmds:
      - docker compose -f docker-compose.dev.yml up --build

  check:
    desc: "lint check"
    deps: [test]
    cmds:
      - uv run --group dev ruff check .
      - uv run --group dev mypy .
      - uv run --group dev bandit -r api

  all-check:
    desc: "all check"
    cmds:
      - docker build -f Dockerfile.check --rm .
