version: "3"
tasks:

  test:
    desc: "python test"
    cmds:
      - uv run --group dev pytest

  local-run:
    desc: "run local dev server"
    cmds:
      - uv run uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload

  local:
    desc: "start local dev server"
    cmds:
      - docker compose -f docker-compose.dev.yml up --build

  check:
    desc: "run all checks"
    cmds:
      - name: linter
        cmd: uv run --group dev ruff check -o "allure-results/ruff-results.xml" .
        ignore_error: true
      - name: type-check
        cmd: uv run --group dev mypy api/
        ignore_error: true
      - name: security-scan
        cmd: uv run --group dev bandit
        ignore_error: true
      - name: test
        cmd: uv run --group dev pytest
        ignore_error: true
      - name: acceptance-tests
        cmd: uv run behave
        ignore_error: true

  all-check:
    desc: "all check"
    cmds:
      - docker build -f Dockerfile.check --rm .

  report:
    desc: "generate allure report"
    cmds:
      - docker compose -f docker-compose.allure.yml up --build
